project = "cloud-resume-project-342521" 
credentials = "./utils/credentials.json" 
name = "cloud-resume-project"
domain = "bolarinwa.dev"
backend_code_path = "archives/backend.zip"
dns_zone_name = "bolarinwa-dev"
